In [1]:
import numpy as np

In [2]:
a=np.array([3 , 2 , 0 , 1 ])
print(np.sort(a))

[0 1 2 3]


In [3]:
b = np.array(['banana' , 'cherry' , 'apple' ])
print (np.sort(b))

['apple' 'banana' 'cherry']


In [4]:
c = np.array([True , False , True ])
print (np.sort(c))

[False  True  True]


# SORTING 2D ARRAYS
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [5]:
ab = np.array([[3 , 2 , 4 ], [5 , 0 , 1 ]])
print(np.sort(ab))

[[2 3 4]
 [0 1 5]]


# NUMPY FILTER ARRAYS

In [6]:
d = np.array([41 , 42 , 43 , 44 ])
x = [True , False , True , False ]
newfilter=d[x]

print(newfilter)

[41 43]


In the example above we hard-coded the Tru e and Fals e values, but the common use is to create a filter
array based on conditions.

In [9]:
e = np.array([41 , 42 , 43 , 44 ])

filter_arr = []

# go through each element in arr
# if the element is higher than 42, set the value to True, otherwise False:

for element in e:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
            
f=e[filter_arr]
print(f)
print(filter_arr)

[43 44]
[False, False, True, True]


In [10]:
#Create a filter array that will return only even elements from the original array:
f1 = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 ])
filter_f1=[]

for element in f1:
    if element % 2 == 0 :
        filter_f1.append(True)
    else:
        filter_f1.append(False)
        
f12=f1[filter_f1]
print(f12)
print(filter_f1)


[2 4 6]
[False, True, False, True, False, True, False]


# Creating Filter Directly From Array

In [12]:
f2= np.array([41 , 42 , 43 , 44 ])
f21 = f2>42

#even
f22 = f2 % 2 == 0

print(f21)
print(f22)

[False False  True  True]
[False  True False  True]
