# Random Numbers in NumPy

# What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not
be predicted logically.

#Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be
some algorithm to generate a random number as well.
If there is a program to generate random number it can be predicted, thus it is not truly random.
Random numbers generated through a generation algorithm are called pseudo random .
Can we make truly random numbers?
Yes. In order to generate a truly random number on our computers we need to get the random data from
some outside source. This outside source is generally our keystrokes, mouse movements, data on network
etc.
We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of
application is the randomness (e.g. Digital roulette wheels).
In this tutorial we will be using pseudo random numbers.

In [6]:
from numpy import random
x=random.randint(100)
print(x)

#Generate a random float from 0 to 1:
y = random.rand()

#float with size
y1=random.rand(5)

print(y)
print(y1)

97
0.22645526955788797
[0.80322715 0.98026153 0.98114013 0.53192428 0.86828203]


In [3]:
#Generate Random Array
#The randint( ) method takes a siz e parameter where you can specify the shape of an array
# below we Generate a 1-D array containing 5 random integers from 0 to 100:
x_array=random.randint(100 , size=(5 ))
print(x_array)

[82 93 15 21 21]


In [5]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x1=random.randint(100, size=(3,5))
print(x1)

[[84 14 72 24 83]
 [21  4 99 21 84]
 [58 25 38 53 87]]


# Generate Random Number From Array

In [8]:
#The choice( ) method allows you to generate a random value based on an array of values.

a=random.choice([3,5,7,9])
print(a)

#Add a siz e parameter to specify the shape of the array.
a1=random.choice([1,3,20,21,34], size=(3,5))
print(a1)

3
[[ 3 21 20  1  1]
 [ 3 21  1 20  1]
 [ 1  3 20 20 34]]
