In [2]:
import numpy as np

In [6]:
arr=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
print(arr[1,1:4])
#for both elements return index 2
print(arr[0:2,2])
#for both elements slice index 1 to 4(not included)
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


#NUMPY DATA TYPES

#NUMPY HAS SOME EXTRA DATATYPES APART FROM THE NATIVE DT TYPES OF PYTHON
#i-INT, b-BOOLEAN, u-UNSIGNED INT, f-FLOAT, c-COMPL FLOAT, m-TIMEDELTA, M-DATETIME, O-OBJECT, S-STRING, U-UNICODE STRING, V -FIXED CHUNK OF MEMORY FOR OTHER TYPE(VOID) 

In [9]:
#CHECKING THE DATATYPE

In [14]:
a=np.array([1,2,3,4])
print(a.dtype)
f=np.array([1,2,3,4], dtype='S')
b=np.array(['apple','banana','nanasi'])
print(b.dtype)
print(f)
print(f.dtype)

int32
<U6
[b'1' b'2' b'3' b'4']
|S1


CONVERT DATA TYPE ON EXISTING ARRAY.
THE BEST WAY TO CHANGE THE DTYPE OF AN EXISTING ARRAY IS TO MAKE A COPY OF THE ARRAY WITH THE ASTYPE() METHOD

In [13]:
c=np.array([1.1,1.2,1.3,2.1])
d=c.astype('i')
e=d.astype(bool)
print(c)
print(d)
print(e)

[1.1 1.2 1.3 2.1]
[1 1 1 2]
[ True  True  True  True]


NUMPY ARRAY COPY VS VIEW

#the main difference btn copy and view of an array is that copy is a new array, and the view is just a view of the original array
#the copy owns the data, changes in og wont affect the copy and vice versa

In [18]:
g=np.array([1,2,3,4])
h=g.copy()
i=g.view()
g[0]=20
print(g)
print(h)
print(i)

[20  2  3  4]
[1 2 3 4]
[20  2  3  4]


#CHECK IF AN ARRAY OWNS ITS DATA BTN THE VIEW AND THE COPY

In [19]:
j=np.array([1,2,3,4])
x=j.copy()
y=j.view()

print(x.base)
print(y.base)

None
[1 2 3 4]
