In [2]:
import numpy as np

In [6]:
arr=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
print(arr[1,1:4])
#for both elements return index 2
print(arr[0:2,2])
#for both elements slice index 1 to 4(not included)
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


#NUMPY DATA TYPES

#NUMPY HAS SOME EXTRA DATATYPES APART FROM THE NATIVE DT TYPES OF PYTHON
#i-INT, b-BOOLEAN, u-UNSIGNED INT, f-FLOAT, c-COMPL FLOAT, m-TIMEDELTA, M-DATETIME, O-OBJECT, S-STRING, U-UNICODE STRING, V -FIXED CHUNK OF MEMORY FOR OTHER TYPE(VOID) 

In [9]:
#CHECKING THE DATATYPE

In [11]:
a=np.array([1,2,3,4])
print(a.dtype)

b=np.array(['apple','banana','nanasi'])
print(b.dtype)

int32
<U6


CONVERT DATA TYPE ON EXISTING ARRAY.
THE BEST WAY TO CHANGE THE DTYPE OF AN EXISTING ARRAY IS TO MAKE A COPY OF THE ARRAY WITH THE ASTYPE() METHOD

In [13]:
c=np.array([1.1,1.2,1.3,2.1])
d=c.astype('i')
e=d.astype(bool)
print(c)
print(d)
print(e)

[1.1 1.2 1.3 2.1]
[1 1 1 2]
[ True  True  True  True]


NUMPY ARRAY COPY VS VIEW