NUMPY SPLITTING ARRAY
Splitting is reverse operation of Joining.
Joining merges multiple arrays into one and Splitting breaks one array into multiple.
We use array_split( ) for splitting arrays, we pass it the array we want to split and the number of splits.

In [6]:
import numpy as np
a = np.array([1 , 2 , 3 , 4 , 5 , 6 ])
b = np.array_split(a, 3)
c = np.array_split(a, 2)
d = np.array_split(a, 4)
print(b)
print(c)
print(d)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Splitting 2-D Arrays

Use the same syntax when splitting 2-D arrays.
Use the array_split( ) method, pass in the array you want to split and the number of splits you want to do

In [10]:
e = np.array([[1 , 2 ], [3 , 4 ], [5 , 6 ], [7 , 8 ], [9 , 10 ], [11 , 12 ]])
e1= np.array_split(e, 3)
print(e1)
print('1st split is :', e1[0])
print('2nd split is :', e1[1])
print('3rd split is :', e1[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
1st split is : [[1 2]
 [3 4]]
2nd split is : [[5 6]
 [7 8]]
3rd split is : [[ 9 10]
 [11 12]]


In [14]:
#Split the 2-D array into three 2-D arrays along rows.

f = np.array([[1 , 2 , 3 ], [4 , 5 , 6 ], [7 , 8 , 9 ], [10 , 11 , 12 ], [13 , 14 , 15 ], [16 , 17 , 18 ]])
print('the dimension of f is:', f.ndim)
f1 = np.array_split(f,3, axis=1)
print(f1)
print(f1[0])
print(f1[0].ndim)

print(f1[1])
print(f1[1].ndim)

print(f1[2])
print(f1[2].ndim)

#An alternate solution is using hsplit( ) opposite of hstack()
f2=np.hsplit(f,3)
print(f2)

#Note: Similar alternates to vstack( ) and dstack( ) are available as vsplit( ) and dsplit( )

the dimension of f is: 2
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
2
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
2
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]
2
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
