# Searching Arrays

In [ ]:
#You can search an array for a certain value, and return the indexes that get a match.
#To search an array, use the where( ) method.

In [1]:
import numpy as np
a = np.array([1 , 2 , 3 , 4 , 5 , 4 , 4 ])
b=np.where(a==4)
print(b)

(array([3, 5, 6], dtype=int64),)


In [3]:
a1=np.where(a==4)
print(a1)

(array([3, 5, 6], dtype=int64),)


In [5]:
#find indexes where value are even
a2=np.where(a%2==0)
print(a2)

(array([1, 3, 5, 6], dtype=int64),)


In [ ]:
#find indexes where value are odd
a3=np.where(a%2==1)

## SEARCH SORTED

There is a method called searchsorted( ) which performs a binary search in the array, and returns the
index where the specified value would be inserted to maintain the search order.
The searchsorted( ) method is assumed to be used on sorted arrays.

In [4]:
c = np.array([ 6 ,7 , 8 , 9])
d = np.array([1 , 3 , 5 , 7 ])
c1=np.searchsorted(c, 10)
c2=np.searchsorted(c, 7, side='right')

c3=np.searchsorted(d, [2,3,6])

print(c1)
print(c2)
print(c3)

4
2
[1 1 3]
