In [ ]:
#Use the floyd_warshall( ) method to find shortest path between all pairs of elements. Negative elements aren't recognized

In [1]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

a= np.array([
    [0 , 8, 0 , 1 ],
    [0 , 0 , 1, 0 ],
    [4 , 0 , 0, 0 ],
    [0 , 2 , 9, 0 ]
])

new_a = csr_matrix(a)
print(floyd_warshall(new_a, return_predecessors=False))

[[0. 3. 4. 1.]
 [5. 0. 1. 6.]
 [4. 7. 0. 5.]
 [7. 2. 3. 0.]]


In [3]:
b=np.array([
    [0, 3, 0, 5],
    [2, 0, 0, 4],
    [0, 1, 0, 0],
    [0, 0, 2, 0]
])

new_b=csr_matrix(b)
print(floyd_warshall(new_b, return_predecessors=False))

[[0. 3. 7. 5.]
 [2. 0. 6. 4.]
 [3. 1. 0. 5.]
 [5. 3. 2. 0.]]
